### ISSUE TITLE
use vim.ui.select and vim.ui.input

### ISSUE THREAD

**Issue by snaggen** [mrcjkb/rustaceanvim#138]
### Feature description

It seems that dialogs like `lua vim.cmd.RustLsp('codeAction')` doesn't use vim.ui.select, which makes custom input like 
https://github.com/stevearc/dressing.nvim and https://github.com/nvim-telescope/telescope-ui-select.nvim, not work.

So, it would be nice if the code actions could (and other relevant parts) could use vim.ui.select (and vim.ui.input when that is appropriate).

**Comment by snaggen** [comment]
For the code action this can be easily worked around by simply using 
```lua
                            vim.keymap.set({ 'n', 'v' }, 'ga', vim.lsp.buf.code_action, { silent = true, buffer = bufnr })
```
But I think this feature request is relevant, since the documentation promotes RustLsp('codeAction')

**Comment by mrcjkb** [comment]
Hey 👋 

rust-analyzer provides code actions with additional "group" information. `:RustLsp codeAction` makes use of that. Afaik, `vim.ui.select` cannot be used to support groups.

I could do the following:

- Fall back to the default handler if there are no grouped code actions available.
- Add this information to the readme.

I'm attending an unconference until Jan 12th, so I might not get around to it until then.

PRs are more than welcome, of course 😃

**Comment by JeanMertz** [comment]
Do you have a list or a link to documentation describing those "groups"? I tried finding them on https://rust-analyzer.github.io/manual.html, but couldn't.

I also switched to using `vim.lsp.buf.code_action` (since I use `dressing.nvim`), but if I'm missing out on valuable actions that are hidden behind a group, I'd probably go back to the custom implementation, even if it often throws me off a bit as I switch between implementations (e.g. when not in a Rust buffer).

**Comment by mrcjkb** [comment]
It's an experimental feature: https://github.com/microsoft/language-server-protocol/issues/994

You shouldn't be missing out on hidden actions with Neovim's built-in code actions.
The `:RustLsp codeAction` command is inherited from rust-tools.nvim. I don't really use it myself, and haven't ever felt like I'm missing out.
