### ISSUE TITLE
FEATURE: Consider updating dap configuration's name and program when switching buffer

### ISSUE THREAD

**Issue by xudyang1** [mrcjkb/rustaceanvim#466]
### Feature description

With the following project structure:
```text
project_root/
├── Cargo.toml
├── target/
├── project1/
|       ├── src/main.rs
|       └── Cargo.toml
└── project2/
         ├── src/main.rs
         └── Cargo.toml
```

Run dap inside `project_root/project1/src/main.rs` will build `project1` and run `project1`. Then, switch to buffer `project_root/project2/src/main.rs` and run dap again, the configuration does not get updated and still debugs project1 (cache is used?).

Currently, I have to exit neovim and run dap in `project2` manually.

If the configuration can be automatically updated, then there is no need to reload neovim or dap configuration manually.

**Comment by mrcjkb** [comment]
Hey :wave: 

This was because rustaceanvim only adds dap configurations when the server reports that it has initialized.
I have changed it to now also add new configurations on LSP attach. Note rust-analyzer may not always be ready to find all the configurations by the time the client has attached. If this happens, you can trigger a reattach with `:e`.
