### ISSUE TITLE
Make `vim.g.rustaceanvim.server.cmd` lazy

### ISSUE THREAD

**Issue by Avi-D-coder** [mrcjkb/rustaceanvim#522]
### Feature description

Make `vim.g.rustaceanvim.server.cmd` only be called lazily after the neovim ui has loaded. 

The configurable function `vim.g.rustaceanvim.server.cmd` is currently called before neovim loads, if this function is blocking the neovim ui will be blank until the function has completed.

### This minimal example will block neovim from loading for 5 seconds:

```lua
  {
    "mrcjkb/rustaceanvim",
    version = "^5", -- Recommended
    lazy = false, -- This plugin is already lazy
    init = function()
      vim.g.rustaceanvim = {
        server = {
          cmd = function()
            os.execute("sleep 5")
            return { "rust-analyzer", "--log-file", "/tmp/rustaceanvim.log" }
          end,
        },
      }
    end,
  },

```

### Real World Use Case: selecting a rust-analyzer version.

This code fixes a common issue, if someone does not include `rust-analyzer` in a projects `rust-toolchain.toml` file running `rust-analyzer` in that project will cause `rustup` to return `error: Unknown binary 'rust-analyzer' in official toolchain '1.79.0-aarch64-apple-darwin'.`

This code attempts to use whatever `rust-analyzer` in the `$PATH`, but falls back to the newer of stable or nightly if we get that error.

The code works, but blocks neovim from loading for a second or two.

```lua
  {
    "mrcjkb/rustaceanvim",

    version = "^5", -- Recommended
    lazy = false, -- This plugin is already lazy
    init = function()
      vim.g.rustaceanvim = {
        server = {
          cmd = function()
            local log_file = "/tmp/rustaceanvim.log"

            local function get_version(output)
              local version = output:match("rust%-analyzer ([%d%.%-%w]+)")
              if version then
                local major, minor, patch = version:match("(%d+)%.(%d+)%.(%d+)")
                if major and minor and patch then
                  return tonumber(major) * 1000000 + tonumber(minor) * 1000 + tonumber(patch)
                end
              end
              return 0
            end

            local function try_rustup(toolchain)
              local output = vim.fn.system("rustup run " .. toolchain .. " rust-analyzer --version")
              if vim.v.shell_error == 0 then
                return get_version(output), toolchain
              end
              return 0, nil
            end

            -- First, try rust-analyzer from PATH
            local path_output = vim.fn.system("rust-analyzer --version")
            if vim.v.shell_error == 0 and not path_output:match("Unknown binary") then
              return { "rust-analyzer", "--log-file", log_file }
            end

            -- Fallback: compare nightly and stable versions
            local best_version = 0
            local best_toolchain = nil

            for _, toolchain in ipairs({ "nightly", "stable" }) do
              local version, tc = try_rustup(toolchain)
              if version > best_version then
                best_version = version
                best_toolchain = tc
              end
            end

            if best_toolchain then
              return {
                "rustup",
                "run",
                best_toolchain,
                "rust-analyzer",
                "--log-file",
                log_file,
              }
            else
              vim.notify("rust-analyzer not found in PATH or through rustup (nightly or stable)", vim.log.levels.ERROR)
              return nil
            end
          end,
```

**Comment by mrcjkb** [comment]
Hey :wave: 

rustaceanvim  lazy-loads on ftplugin. If you open a rust filetype with `nvim foo.rs`, it will load immediately, which is what I presume is what is causing the UI to block for you.

There's not really much I can do in rustaceanvim to serve your use case. The `server.cmd` is evaluated when starting the LSP client, and it will likely just block the UI later if you defer it.
I don't believe it would be a good idea to defer starting the LSP client by default, because that could cause subtle issues (for example, code running after users' `after/ftplugin` scripts).

If you have expensive logic, you can defer it as follows:

- Set `vim.g.rustaceanvim.server.auto_attach` to `false`.
- In `ftplugin/rust.lua`, determine the toolchain asynchronously, using `:h vim.system` and in the callback,
  set the toolchain and start the server.

Example:

```lua
vim.system({"rustup", "run", -- ... }, nil, function(sc)
  if sc.code == 0 then
    local output = sc.stdout
    -- parse output, etc.
  end
end)
```

`vim.system` with a callback doesn't block the UI (it's async and invokes the callback when done),
but you may need to make it recursive to find the best toolchain.

- Set a `vim.g.best_rust_toolchain` variable.
- Change `server.cmd` to retrieve the toolchain from the `vim.g.best_rust_toolchain`  variable.
- Invoke `vim.cmd.RustLsp("start")` in the callback when you've found the best toolchain.
